server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartship_db
    username: postgres
    password: Abc123456 # Mật khẩu của bạn
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379