server:
  port: 8083

spring:
  datasource:
    # Cấu trúc URL: jdbc:postgresql://[host]:[port]/[tên_database]
    url: jdbc:postgresql://localhost:5432/shipment_service_db
    username: postgres
    password: Abc123456
    driver-class-name: org.postgresql.Driver

  jpa:
    # Cấu hình Dialect rất quan trọng để Hibernate hiểu được cú pháp của PostGIS
    hibernate:
      # ddl-auto: update giúp tự động tạo bảng (shipments, package_images) từ Entity của bạn
      ddl-auto: update
    show-sql: true              # Bật cái này lên để xem log SQL, rất tiện khi debug
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

google:
  cloud:
    storage:
      bucket-name: smartship-shipment-danh
      project-id: smartship-backend
      credentials-path: classpath:gcp-service-account.json