// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzcx9pa2_kUmeQoD1EyHHScTDnefixy0M',
    appId: '1:695499497392:web:2ea17bd9c072c847928075',
    messagingSenderId: '695499497392',
    projectId: 'smartship-5cd54',
    authDomain: 'smartship-5cd54.firebaseapp.com',
    storageBucket: 'smartship-5cd54.firebasestorage.app',
    measurementId: 'G-YYFY9P2Z9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_FaLfhodDCY_0COVsMl_IBdPI56EHfjc',
    appId: '1:695499497392:android:ec63220b27dfbf37928075',
    messagingSenderId: '695499497392',
    projectId: 'smartship-5cd54',
    storageBucket: 'smartship-5cd54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg9R7rv2eakKhiyfcZ8XN5QyJO6iePBLM',
    appId: '1:695499497392:ios:7e083b725698652f928075',
    messagingSenderId: '695499497392',
    projectId: 'smartship-5cd54',
    storageBucket: 'smartship-5cd54.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg9R7rv2eakKhiyfcZ8XN5QyJO6iePBLM',
    appId: '1:695499497392:ios:7e083b725698652f928075',
    messagingSenderId: '695499497392',
    projectId: 'smartship-5cd54',
    storageBucket: 'smartship-5cd54.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzcx9pa2_kUmeQoD1EyHHScTDnefixy0M',
    appId: '1:695499497392:web:a660b21df7248d8b928075',
    messagingSenderId: '695499497392',
    projectId: 'smartship-5cd54',
    authDomain: 'smartship-5cd54.firebaseapp.com',
    storageBucket: 'smartship-5cd54.firebasestorage.app',
    measurementId: 'G-J8TE37JYDZ',
  );
}
