server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  application:
    name: shipment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/shipment_service_db
    username: postgres
    password: Abc123456
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    defer-datasource-initialization: true

  docker:
    compose:
      enabled: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

google:
  cloud:
    storage:
      bucket-name: smartship-shipment-danh
      project-id: smartship-backend
      credentials-path: classpath:gcp-service-account.json

# ================= VNPAY CONFIG =================
vnpay:
  tmnCode: 18LYBG10
  hashSecret: 803GSXDSSBGRF9CX9CLPO659AA6SF4PR
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  # Link này VNPay sẽ gọi về sau khi khách quét mặt hoặc quẹt thẻ xong (Qua cổng API Gateway 8080)
  returnUrl: http://192.168.1.16:8080/shipments/payments/vnpay-return

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG         # In ra toàn bộ câu lệnh SQL chạy ngầm
    org.hibernate.orm.jdbc.bind: TRACE # In ra chính xác các giá trị (tham số) truyền vào DB
    org.springframework.web: DEBUG   # Theo dõi sát sao các request gọi từ Frontend vào Controller