server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/location_service_db
    username: postgres
    password: Abc123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/smartship_location

    redis:
      host: localhost
      port: 6379
      password: